version: "2.1"

commands:
  fail_fast:
    steps:
      - run:
          name: 'Fail Fast'
          when: on_fail
          command: |
            echo "Canceling workflow as a step resulted in failure"
            curl -X POST --header "Content-Type: application/json" "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/cancel?circle-token=${CIRCLE_TOKEN}"          

jobs:

  test:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo $CIRCLE_TOKEN
      - run: echo $CIRCLE_WORKFLOW_ID    

  Setup:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  validate:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  lint:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - run: echo "Hello World"

  build:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
      - run: sleep 20
      - run: exit 1

  e2e-cli:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
      - fail_fast

  test:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
      - fail_fast

  test-browsers:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
      - fail_fast

  e2e-cli-ng-snapshots:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
      - fail_fast

  e2e-cli-node-12:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
      - fail_fast

  e2e-cli-win:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
      - fail_fast

  snapshot_publish:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
      - fail_fast

workflows:
  Test:
    jobs:
      - Setup
      - validate:
          requires:
            - Setup
      - lint:
          requires:
            - Setup
      - build:  
          requires:
            - Setup
      - e2e-cli:
          requires:
            - build
      - test:
          requires:
            - build
      - test-browsers:
          requires:
            - build
      - e2e-cli-ng-snapshots:
          requires:
            - e2e-cli
      - e2e-cli-node-12:
          requires:
            - e2e-cli
      - e2e-cli-win:
          requires:
            - test
      - snapshot_publish:
          requires:
            - e2e-cli
            - build
            - test
