version: "2.1"
jobs:
  Setup:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  validate:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  lint:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - run: sleep 10
      - run: exit 1
  build:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
      - run:
          name: Fail Fast
          when: on_fail
          command: |
            echo "Canceling workflow as a step resulted in failure"
            curl -X POST --header "Content-Type: application/json" "https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/cancel?circle-token=${CIRCLE_TOKEN}" 
  e2e-cli:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  test:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  test-browsers:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  e2e-cli-ng-snapshots:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  e2e-cli-node-12:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  e2e-cli-win:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  snapshot_publish:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"


workflows:
  Test:
    jobs:
      - Setup
      - validate:
          requires:
            - Setup
      - lint:
          requires:
            - Setup
      - build:  
          requires:
            - Setup
      - e2e-cli:
          requires:
            - build
      - test:
          requires:
            - build
      - test-browsers:
          requires:
            - build
      - e2e-cli-ng-snapshots:
          requires:
            - e2e-cli
      - e2e-cli-node-12:
          requires:
            - e2e-cli
      - e2e-cli-win:
          requires:
            - test
      - snapshot_publish:
          requires:
            - e2e-cli
            - build
            - test
