version: 2.1
commands:
  fail_fast:
    steps:
      - run:
          name: Fail job if others have failed
          command: |
            STATUS=$(curl "https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID?circle-token=$CIRCLE_TOKEN" | jq -r '.status')
            if [[ "$STATUS" == "failing" ]]; then
              exit 1
            else
              exit 0
            fi
jobs:
  test:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - fail_fast
      - run: exit 1
  test2:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - fail_fast
      - run: sleep 20
  test3:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: sleep 30
      - fail_fast
      - run: sleep 10
      - fail_fast
      - run: echo hi
workflows:
  all-tests:
    jobs:
      - test
      - test2
      - test3
